import java.util.Random;
import java.util.Scanner;
import java.text.DecimalFormat;


public class MethodPay
{
	// This program will generate the Period Pay using many methods
	// Generated by Veeral Patel, CISC230

	public static void main(String[] args)
	{
		Random randomNum = new Random();
		DecimalFormat dform = new DecimalFormat ("0.##");
		Scanner keyboard = new Scanner(System.in);

		String lastName, firstName, bankName;
		double yearlySalary, insurancePlan, payMethod, basePay, taxInfo, deduction, plan, payEmployee, finalPay;
		String electronicPay, checkingPay;
		long accountNumber;
		Intro();

		firstName = getFirstName(keyboard);
		lastName = getLastName(keyboard);
		bankName = getBankName(keyboard);
		yearlySalary = getYearlySalary(keyboard);
		accountNumber = getAccountNumber(keyboard);
		insurancePlan = getInsurancePlan(keyboard);
		payMethod = getPayMethod(keyboard);
		basePay = getBasePay(yearlySalary);
		taxInfo = getTaxes(yearlySalary, basePay);
		deduction = getBasePay(yearlySalary);
		finalPay = genPay(basePay, taxInfo, insurancePlan);
		getPayEmployee(payMethod, finalPay, firstName, lastName, accountNumber, bankName);
		elecPay(finalPay, firstName, lastName, accountNumber, bankName);
		checkPay(finalPay, firstName, lastName);

	}

	static void Intro()
	{
		System.out.println("Welcome to Veeral's Payroll Application");
	}
	static String getLastName(Scanner keyboard)
	{
		String last;

		System.out.println();
		System.out.println("Please Enter Last Name");
		last = keyboard.nextLine();
		return last;
	}
	static String getFirstName(Scanner keyboard)
	{
		String first;
		System.out.println();
		System.out.println("Please Enter First Name");
		first = keyboard.nextLine();
		return first;
	}
	static String getBankName(Scanner keyboard)
	{
		String bank;
		System.out.println();
		System.out.println("Please Enter Bank Name");
		bank = keyboard.nextLine();
		return bank;
	}
	static long getAccountNumber(Scanner keyboard)
	{
		long accountNum;
		System.out.println();
		System.out.println("Enter Account Number");
		accountNum = keyboard.nextLong();
		return accountNum;
	}
	static double getYearlySalary(Scanner keyboard)
	{
		double yearlySal;
		System.out.println();
		System.out.println("Enter Yearly Salary");
		yearlySal = keyboard.nextDouble();
		return yearlySal;
	}
	static double getInsurancePlan(Scanner keyboard)
	{
		double insurance, plan;
		System.out.println();
		System.out.println("Enter Either 1,2,3 for Insurance Plan");
		insurance = keyboard.nextDouble();
		plan = 0;
		if (insurance == 1)
		{
			plan = 300;
		}
		if (insurance == 2)
		{
			plan = 200;
		}
		if (insurance == 3)
		{
			plan = 100;
		}
		return plan;
	}
	static double getPayMethod(Scanner keyboard)
	{
		double pay;
		System.out.println();
		System.out.println("Enter Pay Method, 1 = electronic ... 2 = check");
		pay = keyboard.nextDouble();
		return pay;
	}
	static double getBasePay(double yearlySalary)
	{
		double biWeekPay;
		biWeekPay = yearlySalary/26;
		return biWeekPay;
	}
	static double getTaxes (double yearlySalary, double basePay)
	{
			double FICA, fedTax, stateTax, fedTax1, stateTax1, fedTax2, stateTax2, end;

			FICA = basePay*.05;
			fedTax = basePay*.05;
			stateTax = basePay*.03;
			fedTax1 = basePay*.08;
			stateTax1 = basePay*.04;
			fedTax2 = basePay*.1;
			stateTax2 = basePay*.05;
			end = 0;


			if ( yearlySalary < 40000)
			{
				end = fedTax+stateTax+FICA;
			}

			if ( yearlySalary >= 40000 && yearlySalary < 150000)
			{
				end = fedTax1+stateTax1+FICA;
			}

			if ( yearlySalary >= 150000)
			{
				end = fedTax2+stateTax2+FICA;
			}
			return end;
	}
	static double genPay (double basePay, double getTaxes, double getInsurancePlan)
	{
		basePay = basePay - (getTaxes + getInsurancePlan);
		return basePay;
	}
	static void getPayEmployee (double payMethod, double finalPay, String firstName, String lastName, long accountNumber, String bank)
	{

		if (payMethod == 1)
		{
			elecPay(finalPay, firstName, lastName, accountNumber, bank);
		}
		if (payMethod == 2)
		{
			checkPay(finalPay, firstName, lastName);
		}
	}
	static void elecPay ( double finalPay, String firstName, String lastName, long accountNumber, String bank)
	{
		System.out.println();
		System.out.println("Name: " + firstName + " " + lastName);
		System.out.println("Bank: " + bank);
		System.out.println("Account Number: " + accountNumber);
		System.out.println("Pay Amount for this period (2 weeks) is: " + finalPay);
	}
	static void checkPay (double finalPay, String firstName, String lastName)
	{
		System.out.println();
		System.out.println("Name: " + firstName + " " + lastName);
		System.out.println("Pay Amount: " + finalPay);
	}


}

